### ISSUE TITLE
Windows: cannot delete typed characters

### ISSUE THREAD

**Issue by tuananh** [chriswalz/bit#29] opened 2020-10-12 07:06 UTC
version: install with go
terminal: Windows Powershell with Windows Terminal app
os: windows 10

## steps to reproduce

```bash
cd <repo>
bit
# type puss <--- typo
# cannot backspace to delete 
```

**Comment by MsBarber** [comment] 2020-10-12 15:56
I am also using Windows 10 OS.
I am using the Windows Terminal App, in the Powershell tab. 

Only potential difference is that I am using WSL (Ubuntu 18.04). Bit (which is amazing) works properly for me.

I can try installing it on Windows instead of WSL later today and report back if I experience the same issue.

**Comment by chriswalz** [comment] 2020-10-12 16:31
@tuananh This one may take a while to solve and I would appreciate help on this front since I'm pretty confident this is bug in [go-prompt](https://github.com/c-bata/go-prompt) the library bit uses to display suggestions

**Comment by codingonHP** [comment] 2020-10-14 03:00
I tried to reproduce this on my Windows 10 Enterprise (Version: 1909, OS Build: 18363.1139)
with Powershell running inside the Windows Terminal app
```
Windows Terminal
Version: 1.3.2651.0

```
but couldn't. It works fine for me. I am able to correct my typos. Checked the same scenarios with `powershell`, `git bash` and `cmd` and it works fine there as well.

**Comment by chriswalz** [comment] 2020-10-14 21:21
@tuananh I believe this is fixed now. Please verify on v0.6.1

**Closed** 2020-10-14 21:21 UTC
Labels: bug, help wanted
